<a href="https://colab.research.google.com/github/ximenaOr7/ximenaob_mineria/blob/main/miner%C3%ADa_de_datos_cuaderno_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Minería de datos

##Primer parcial

###Introducción

####conceptos

#####ciencia de datos

######Ciencia de datos

In [ ]:
def donothing(x):
    return x

76.9 µs ± 10.1 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
#el comando magico %timeit sirve para evaluar
#el desempeño en terminos de tiempo
%timeit L = [n ** 2 for n in range(1000)]


88.6 µs ± 27.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


python and shell commands

In [ ]:
!ls

sample_data/


In [ ]:
!cd sample_data/

In [ ]:
%ls

Understanding data types in puthon

In [ ]:
import numpy as np

In [ ]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [4]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [5]:
print("dtype:", x3.dtype) # dtype nos dice el tipo de datos


dtype: int64


In [6]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


Array Indexing: Accessing Single Elements / 26 enero 2026

In [7]:
x1

array([5, 0, 3, 3, 7, 9])

In [9]:
x1[0]


np.int64(5)

In [10]:
x1[4] #colocamos el índice del elemento a extraer de la lista


np.int64(7)

In [12]:
x1[-1]


np.int64(9)

In [13]:
x2


array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [15]:
x2[2, 0]


np.int64(1)

In [17]:
x2[0, 0] = 12 #asignar un nuevo valor (12) al renglón 0 columna 0
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

#####estadística básica

NumPy proporciona una estructura de datos eficiente basada en arreglos (ndarray) y un amplio conjunto de funciones matemáticas y estadísticas que permiten:

Resumir datos rápidamente
Calcular medidas de tendencia central
Analizar la dispersión
Trabajar con arreglos multidimensionales

In [18]:
import numpy as np


In [19]:
#Media (Mean)

data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


In [22]:
#Promedio (Average) y Promedio Ponderado

data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

In [21]:
#mediana
mediana = np.median(data)


In [23]:
#Varianza y Desviación Estándar
varianza = np.var(data)
desviacion = np.std(data)

In [24]:
#🔄 Generación de Datos Aleatorios
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra))

-0.006543456960417206 1.0059985778093545


In [25]:
#correlación
corr = np.corrcoef([1,2,3], [1,5,7])